name: Exécuter les tests unitaires Java

on:
  push:
    branches:
      - '*'

jobs:
  tests:
    name: Exécuter les tests unitaires
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code source
        uses: actions/checkout@v1

      - name: Configuration de l'environnement Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Version de Java que vous souhaitez utiliser
          distribution: 'adopt'  # Distribution Java, par exemple, AdoptOpenJDK

      - name: Compilation du projet
        run: |
         mvn clean install

      - name: Exécution des tests unitaires
        run: |
          mvn test

    # Ajoutez d'autres étapes si nécessaire, telles que la génération de rapports, la notification des résultats, etc.
